options {
    directory "__RUNTIME_STATE_DIR__";
    listen-on port 55301 { 127.0.0.1; };
    listen-on-v6 { none; };
    recursion yes;
    dnssec-validation no;
    allow-query { any; };
    allow-recursion { any; };
    pid-file "named.pid";
    session-keyfile "session.key";
    statistics-file "named.stats";
    dump-file "named.dump";
    memstatistics-file "named.memstats";
    forward only;
    forwarders { 127.0.0.1 port 55300; };
};
logging {
    channel default_stderr {
        stderr;
        severity info;
    };
    category default { default_stderr; };
};
