options {
    directory "/home/ubuntu/symcc/named_experiment/runtime";
    listen-on port 55301 { 127.0.0.1; };
    listen-on-v6 { none; };
    recursion yes;
    dnssec-validation no;
    allow-query { any; };
    allow-recursion { any; };
    pid-file "/home/ubuntu/symcc/named_experiment/runtime/named.pid";
    session-keyfile "/home/ubuntu/symcc/named_experiment/runtime/session.key";
    statistics-file "/home/ubuntu/symcc/named_experiment/runtime/named.stats";
    dump-file "/home/ubuntu/symcc/named_experiment/runtime/named.dump";
    memstatistics-file "/home/ubuntu/symcc/named_experiment/runtime/named.memstats";
    forward only;
    forwarders { 127.0.0.1 port 55300; };
};
logging {
    channel default_stderr {
        stderr;
        severity info;
    };
    category default { default_stderr; };
};
